welcome_text:
  Ger: >
    ## ‚õΩ Willkommen zum Benzinpreis Forecaster ‚õΩ

    Die Benzinpreise an deutschen Tankstellen ver√§ndern sich mehrmals t√§glich mit Teils extremen Preisspr√ºngen. Daneben tragen langfristige Trends der √ñlm√§rkte zur Intransparenz der Benzinpreise bei. Ziel dieser App ist daher, euch zu helfen mehr Transparenz √ºber die Preise eurer Tankestelle(n) zu liefern, damit ihr g√ºnstiger tanken k√∂nnt.
    
  
    Aktuell unterst√ºtzt die App folgende Features:

    * **Prognose:** Sehe den prognostizierten Benzinpreisverlauf der n√§chsten 24h f√ºr deine Tankstelle. Daneben findest du weitere spannende Insights zu den Benzinpreisen deiner Tankstelle.

    * **Karten:** üöß Coming soon. üöß

    * **Freie Analyse:** üöß Coming soon. üöß


    Viele Spa√ü bei der Nutzung der App!

    <div class="info-box">
    Die App wurde mit Hilfe der offenen API von [Tankerk√∂nig](https://creativecommons.tankerkoenig.de/)) umgesetzt. Die App besteht aus verschiedenen (selbst-entwickelten) Services, deren Source Code hier einsehbar ist: 

    - [Cloud Storage Wrapper](https://github.com/ja-ba/Cloud-Storage-Wrapper): ein Wrapper Package zum Datenaustausch mit der (kostenlosen) Oracle Cloud.
    - [TPA-Data-Processor](https://github.com/ja-ba/TPA-Data-Processor): Implementiert die ETL Strecken √ºber [Apache Airflow](https://airflow.apache.org/) 
    - [TPA-Analytics-Engine](https://github.com/ja-ba/TPA-Analytics-Engine): eine Engine zur Echtzeitprognose der Benzinpreise.
    - [TPA-Frontend](https://github.com/ja-ba/TPA-Frontend): Implementiert das Frontend der App in [Streamlit](https://streamlit.io/)
    </div>

    Ich freue mich √ºber Feedback, Hinweise auf Bugs und Verbesserungsvorschl√§ge an : jakobs.dataprojects@gmail.com

  Eng: >
    ## ‚õΩ Welcome to the Gas Price Forecaster ‚õΩ
    Gas prices at German gas stations change several times a day with often extreme price jumps. In addition, long-term trends in the crude oil market contribute to the lack of transparency in gas prices. The goal of this app is to help you gain more transparency over the prices at your gas station(s) so that you can refuel more cheaply.


    Currently, the app supports the following features:

    * **Forecast:** See the predicted gas price trend for the next 24 hours for your gas station. You will also find other exciting insights about the gas prices at your gas station.

    * **Maps:** üöß Coming soon. üöß

    * **Free Analysis:** üöß Coming soon. üöß


    Have fun using the app!

    The app was implemented with the help of the open API from [Tankerk√∂nig](https://creativecommons.tankerkoenig.de/). The app consists of various (self-developed) services, whose source code can be viewed here:

    <div class="info-box">
    - [Cloud Storage Wrapper](https://github.com/ja-ba/Cloud-Storage-Wrapper): a wrapper package for data exchange with the (free) Oracle Cloud.
    - [TPA-Data-Processor](https://github.com/ja-ba/TPA-Data-Processor): Implements the ETL pipelines via [Apache Airflow](https://airflow.apache.org/)
    - [TPA-Analytics-Engine](https://github.com/ja-ba/TPA-Analytics-Engine): an engine for real-time gas price forecasting.
    - [TPA-Frontend](https://github.com/ja-ba/TPA-Frontend): Implements the app's frontend in [Streamlit](https://streamlit.io/)
    </div>

    I appreciate feedback, bug reports, and suggestions for improvement at: jakobs.dataprojects@gmail.com


sidebar_upper:
  Ger :
    Auswahl : 0
    Wilkommen: "welcome"
    Prognose: "forecast"
    # Karten (coming soon...): "maps"
    # Freie Analyse (coming soon...): "free"
  Eng :
    Selection : 0
    Welcome: "welcome"
    Forecast: "forecast"
    # Maps (coming soon...): "maps"
    # Free Deep Dive (coming soon...): "free"
  symbols: ["house", "bar-chart-line"] # , "map", "rulers"

sidebar_lower:
  forecast:
    Ger: ["Bitte w√§hlen Sie eine Tankstelle aus? Tippen Sie einfach einen Namen, Ort oder PLZ in das Feld", "Sie k√∂nnen z.B, 'Shell Bonner Str.' eingeben um eine konkrete Tankstelle zu suchen oder '12057' eingeben um alle Tankstellen in diesem PLZ Gebiet angezeigt zu bekommen", "Bitte w√§hlen Sie eine Sorte?", "Neue Tankstellen Suche"]
    Eng: ["Please select a gas station by typing a name, location or postal code", "You can type e.g. 'Shell Bonner Str.' to search for a specific gas station or '12057' to show all gas stations in this postal code area", "Please select a gas type?", "New Gas Station Search"]
  maps:
    Ger: ["Bitte w√§hlen Sie eine Woche aus!"]
    Eng: ["Please select a week!"]

forecast:
  Ger:
    please_choose: "Bitte w√§hle in der linken Leiste eine Tankstelle aus!"
    tab_title1: "Prognose n√§chste 24h"
    tab_title2: "Preiseinfl√ºsse"
    page_title_forecast: "### Wie wird sich der Preis in den n√§chsten 24h entwickeln?"
    y_title: "Preis in ‚Ç¨/Liter"
    x_title: "Uhrzeit"
    page_title_impact: "## Wodurch wird der Preis beeinflusst?"
    y_title_barchart: "Preisdifferenz zum Durchschnitt"
    chart_title_hour: "Preiseinfluss: Tageszeit"
    x_title_hour: "Tageszeit"
    chart_title_weekday: "Preiseinfluss: Wochentag"
    x_title_weekday : "Wochentag"
    chart_title_trend: "Langfristiger Trend"
    x_title_trend: "Kalenderwoche"
    legend_forecast: "Vorhersage Preis"
    legend_yesterday: "Tats√§chlicher Preis<br>in letzten 24h"
    legend_name: "Legende"
    weekday_list: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"]
    tbd11: "‚ö†Ô∏è Das hat leider nicht geklappt. F√ºr die ausgew√§hlte Tankstelle und/oder Sorte gibt es keine Daten. Bitte versuche eine andere Tankstelle oder Sorte! ‚ö†Ô∏è"
    tbd12: "‚ö° Die Berechnung dieses Models hat "
    tbd13: " Sekunden gedauert ‚ö°"


  Eng:
    please_choose: "Please select a gas station in the left sidebar!"
    tab_title1: "Price forecast for the next 24h"
    tab_title2: "Price influences"
    page_title_forecast: "### How will the price develop in the next 24h?"
    y_title: "Price in ‚Ç¨/Liter"
    x_title: "Time"
    page_title_impact: "## What influences the price?"
    y_title_barchart: "Price difference to the average"
    chart_title_hour: "Price influence: Time of day"
    x_title_hour: "Time of day"
    chart_title_weekday: "Price influence: Weekday"
    x_title_weekday : "Day of week"
    chart_title_trend: "Long-term trend"
    x_title_trend: "Calendar week"
    legend_forecast: "Forecasted price"
    legend_yesterday: "Actual price in<br>the last 24h"
    legend_name: "Legend"
    weekday_list: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    tbd11: "‚ö†Ô∏è Unfortunately, there is no data for the selected gas station and/or type. Please try another gas station or type! ‚ö†Ô∏è"
    tbd12: "‚ö° The calculation of this model took "
    tbd13: " seconds ‚ö°"

markdown:
  german_flag: >
    <style>
    div:nth-child(3) > div > div > label:nth-child(1) > div:nth-child(3) {
      background-image: url("https://cdn-icons-png.flaticon.com/512/330/330523.png");
      background-size: cover;
      font-size: 0;
      height: 30px;
      width: 30px;
    }
    </style>
  english_flag: >
    <style>
    div:nth-child(3) > div > div > label:nth-child(2) > div:nth-child(3) {
      background-image: url("https://cdn-icons-png.flaticon.com/512/3013/3013911.png");
      background-size: cover;
      font-size: 0;
      height: 30px;
      width: 30px;
    }
    </style>
